### PR TITLE
C++/WinRT now handles failing async/event delegates the same way that WRL does

### LINKED ISSUE #409: C++/WinRT should handle disconnected async completion handlers much like it does event handlers

### PR DESCRIPTION
**Pull request by kennykerr**
Fixes #409

### CODE REVIEW

File: src/tool/cppwinrt/strings/base_events.h [hunk 1]
```diff
@@ -335,6 +335,29 @@ namespace winrt::impl
...
+    bool invoke(Delegate const& delegate, Arg const&... args) noexcept
+    {
+        try
+        {
+            delegate(args...);
+        }
+        catch (...)
+        {
+            int32_t const code = to_hresult();
+            WINRT_RoTransformError(code, 0, nullptr);
```
Comment (devhawk) [inline src/tool/cppwinrt/strings/base_events.h]: Why are we adding RoTransformError here?

Comment (kennykerr) [reply src/tool/cppwinrt/strings/base_events.h]: This adds telemetry so that instead of the error info simply disappearing when the exception is destroyed (and the ref count reaches zero), there is an event indicating that the error was transformed explicitly.
